// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"blog-admin/app/model/internal"
)

// BlogTimeline is the golang structure for table blog_timeline.
type BlogTimeline internal.BlogTimeline

// Fill with you ideas below.