// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"blog-admin/app/dao/internal"
)

// blogTimelineDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type blogTimelineDao struct {
	*internal.BlogTimelineDao
}

var (
	// BlogTimeline is globally public accessible object for table blog_timeline operations.
	BlogTimeline = &blogTimelineDao{
		internal.BlogTimeline,
	}
)

// Fill with you ideas below.